#nullable enable
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Chievfx.Mcp.Editor
{
    internal sealed class ChievfxMcpPromptService : BridgeDomainServiceBase
    {
        private readonly SceneResourceService sceneResources;

        public ChievfxMcpPromptService(SceneResourceService sceneResources)
        {
            this.sceneResources = sceneResources;
        }

            public object GetPrompt(JToken args)
            {
                var name = ReadString(args, "name");
                if (string.IsNullOrWhiteSpace(name))
                {
                    throw new ArgumentException("name is required.", nameof(name));
                }

                return name switch
                {
                    "unity-editor-context" => GetUnityEditorContextPrompt(args),
                    _ => throw new InvalidOperationException($"Unknown ChievFX MCP prompt '{name}'.")
                };
            }

            private object GetUnityEditorContextPrompt(JToken args)
            {
                var promptArgs = args["arguments"] as JObject ?? new JObject();
                var focus = ReadString(promptArgs, "focus");
                var context = sceneResources.ReadEditorContextResource("chievfx://editor/context");
                var contextJson = JsonConvert.SerializeObject(context, Formatting.Indented);
                var focusLine = string.IsNullOrWhiteSpace(focus)
                    ? "No specific focus provided."
                    : $"Focus: {focus}";
                var text =
                    "Use this live Unity Editor context to decide the next useful inspection or implementation step.\n\n" +
                    focusLine +
                    "\n\nEditor context JSON:\n" +
                    contextJson +
                    "\n\nReturn concise observations, likely risks, and concrete next MCP reads/tools to run if more evidence is needed.";

                return new
                {
                    description = "Dynamic Unity editor context prompt generated by the ChievFX bridge.",
                    messages = new object[]
                    {
                        new
                        {
                            role = "user",
                            content = new
                            {
                                type = "text",
                                text
                            }
                        }
                    }
                };
        }
    }
}
