#nullable enable
using System;
using System.IO;
using System.Text;
using UnityEngine;

namespace Chievfx.Mcp.Editor
{
    // MCP client configs must point at a path that survives package re-resolution. The real server lives
    // under Library/PackageCache/com.chievfx.mcp@<hash>/ (or Packages/ when embedded); Unity's <hash> is
    // derived from the resolved source revision, so it changes when the package is updated — baking it
    // into a config breaks the client until someone re-writes it. Instead the config points at this tiny
    // launcher, written to the fixed bridge dir, which resolves the CURRENT server at launch time.
    //
    // It stays per-project: it only looks inside this project's own Packages/ and Library/PackageCache,
    // so each project still runs (and keeps the instructions of) its own package copy.
    internal static class ChievfxMcpServerLauncher
    {
        private const string LauncherContent =
@"#!/usr/bin/env python3
# Auto-generated by ChievFX MCP. Do not edit.
# Runs this project's chievfx_mcp_server.py. Prefers the package Unity imported (embedded Packages/,
# or Library/PackageCache/com.chievfx.mcp@<hash>/ whose hash changes on update), and falls back to a
# committed .tgz so it still works before/without Unity having imported the package (fresh clone,
# another machine, or while Unity is re-resolving the package).
import glob
import os
import sys
import tarfile

_REL_SERVER = os.path.join('Tools~', 'ChievfxMcp', 'chievfx_mcp_server.py')


def _here():
    return os.path.dirname(os.path.abspath(__file__))


def _project_root():
    # This file lives at <projectRoot>/Library/ChievfxMcpBridge/launch_server.py
    return os.path.dirname(os.path.dirname(_here()))


def _installed_server(root):
    # Embedded package (Packages/) has a stable path; prefer it, then the PackageCache copy.
    embedded = os.path.join(root, 'Packages', 'com.chievfx.mcp', _REL_SERVER)
    if os.path.isfile(embedded):
        return embedded
    hits = [p for p in glob.glob(os.path.join(root, 'Library', 'PackageCache', 'com.chievfx.mcp@*', _REL_SERVER)) if os.path.isfile(p)]
    hits.sort(key=os.path.getmtime, reverse=True)
    return hits[0] if hits else None


def _committed_tarball(root):
    hits = []
    for base in ('PackagesSource', 'Assets', 'Packages'):
        hits += glob.glob(os.path.join(root, base, '**', 'com.chievfx.mcp-*.tgz'), recursive=True)
    hits = [p for p in hits if os.path.isfile(p)]
    hits.sort(key=os.path.getmtime, reverse=True)
    return hits[0] if hits else None


def _server_from_tarball(tgz):
    # Extract the server tree once, into a cache keyed by the tarball filename (which changes per
    # build), so a rebuilt/pulled .tgz re-extracts and stale caches are dropped.
    stem = os.path.splitext(os.path.basename(tgz))[0]
    cache_root = os.path.join(_here(), 'server-cache')
    out = os.path.join(cache_root, stem)
    server = os.path.join(out, 'package', _REL_SERVER)
    if not os.path.isfile(server):
        os.makedirs(out, exist_ok=True)
        with tarfile.open(tgz) as tar:
            members = [m for m in tar.getmembers() if m.name.startswith('package/Tools~/')]
            try:
                tar.extractall(out, members, filter='data')
            except TypeError:
                tar.extractall(out, members)
        if os.path.isdir(cache_root):
            import shutil
            for name in os.listdir(cache_root):
                if name != stem:
                    shutil.rmtree(os.path.join(cache_root, name), ignore_errors=True)
    return server if os.path.isfile(server) else None


def _run(server):
    argv = [sys.executable, server] + sys.argv[1:]
    # Windows has no true exec: os.execv spawns a NEW pid and exits this process, so the MCP client
    # (which tracks the process it spawned) sees the server die and the stdio pipe break. Stay resident
    # as a thin parent and let the child inherit our stdin/stdout/stderr instead. On macOS/Linux execv
    # is a real image replacement (same pid, same handles), which the client wants — so keep it there.
    if os.name == 'nt':
        import subprocess
        raise SystemExit(subprocess.run(argv).returncode)
    os.execv(sys.executable, argv)


def main():
    root = _project_root()
    server = _installed_server(root)
    if server is None:
        tgz = _committed_tarball(root)
        if tgz is not None:
            server = _server_from_tarball(tgz)
    if server is None:
        sys.stderr.write('ChievFX MCP launcher: could not find chievfx_mcp_server.py under Packages/, Library/PackageCache/, or a committed com.chievfx.mcp-*.tgz. Open the project in Unity so the package imports.\n')
        sys.exit(1)
    _run(server)


if __name__ == '__main__':
    main()
";

        // Writes the launcher to the bridge dir (idempotent). Call before writing client configs and on
        // bridge start so the path a config references always exists.
        public static void EnsureLauncherWritten()
        {
            try
            {
                WriteLauncherTo(ChievfxMcpToolPolicy.LauncherScriptPath);
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"ChievFX MCP could not write the server launcher. {ex.Message}");
            }
        }

        // Idempotent write of the launcher to an explicit path. The content is project-agnostic (it derives
        // its project root from its own location), so the same bytes serve a secondary project whose own
        // Unity has not written one yet. Throws — callers report their own context.
        public static void WriteLauncherTo(string path)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            if (!File.Exists(path) || !string.Equals(File.ReadAllText(path), LauncherContent, StringComparison.Ordinal))
            {
                File.WriteAllText(path, LauncherContent, new UTF8Encoding(false));
            }
        }
    }
}
