#nullable enable
using System;
using System.IO;
using System.Text;
using UnityEngine;

namespace Chievfx.Mcp.Editor
{
    // MCP client configs must point at a path that survives package re-resolution. The real server lives
    // under Library/PackageCache/com.chievfx.mcp@<hash>/ (or Packages/ when embedded); Unity's <hash> is
    // derived from the resolved source revision, so it changes when the package is updated — baking it
    // into a config breaks the client until someone re-writes it. Instead the config points at this tiny
    // launcher, written to the fixed bridge dir, which resolves the CURRENT server at launch time.
    //
    // It stays per-project: it only looks inside this project's own Packages/ and Library/PackageCache,
    // so each project still runs (and keeps the instructions of) its own package copy.
    internal static class ChievfxMcpServerLauncher
    {
        private const string LauncherContent =
@"#!/usr/bin/env python3
# Auto-generated by ChievFX MCP. Do not edit.
# Resolves this project's current chievfx_mcp_server.py and runs it. The
# Library/PackageCache hash changes when the package is updated/re-resolved, so
# the MCP client config points here (a stable path) instead of a hashed path.
import glob
import os
import sys


def _project_root():
    # This file lives at <projectRoot>/Library/ChievfxMcpBridge/launch_server.py
    return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _find_server(root):
    # Embedded package (Packages/) has a stable path; prefer it.
    embedded = os.path.join(root, 'Packages', 'com.chievfx.mcp', 'Tools~', 'ChievfxMcp', 'chievfx_mcp_server.py')
    if os.path.isfile(embedded):
        return embedded
    # Otherwise the registry/git copy in this project's PackageCache (hashed dir).
    pattern = os.path.join(root, 'Library', 'PackageCache', 'com.chievfx.mcp@*', 'Tools~', 'ChievfxMcp', 'chievfx_mcp_server.py')
    matches = [p for p in glob.glob(pattern) if os.path.isfile(p)]
    matches.sort(key=os.path.getmtime, reverse=True)
    return matches[0] if matches else None


def main():
    server = _find_server(_project_root())
    if server is None:
        sys.stderr.write('ChievFX MCP launcher: chievfx_mcp_server.py not found under Packages/ or Library/PackageCache/.\n')
        sys.exit(1)
    os.execv(sys.executable, [sys.executable, server] + sys.argv[1:])


if __name__ == '__main__':
    main()
";

        // Writes the launcher to the bridge dir (idempotent). Call before writing client configs and on
        // bridge start so the path a config references always exists.
        public static void EnsureLauncherWritten()
        {
            try
            {
                var path = ChievfxMcpToolPolicy.LauncherScriptPath;
                Directory.CreateDirectory(Path.GetDirectoryName(path)!);
                if (!File.Exists(path) || !string.Equals(File.ReadAllText(path), LauncherContent, StringComparison.Ordinal))
                {
                    File.WriteAllText(path, LauncherContent, new UTF8Encoding(false));
                }
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"ChievFX MCP could not write the server launcher. {ex.Message}");
            }
        }
    }
}
